split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 42

augment_fn:
  name: resize_aug
  parameters:
    p: 1
    height: 512
    width: 512

normalize_fn:
  name: identity

denormalize_fn:
  name: identity

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 32
    val_bs: 64
    test_bs: 64
    num_workers: 0

sampler:
  name: WeightedRandomSampler
  parameters:
    replacement: true

model:
  name: cbam_resnet18_four_channel_input_one_fc

loss_func:
  - name: FocalLoss
  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_1
  parameters:
    epochs: 30



