split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 42

augment_fn:
  name: resize_aug
  parameters:
    p: 1
    height: 64
    width: 64

normalize_fn:
  name: identity

denormalize_fn:
  name: identity

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 2
    val_bs: 2
    test_bs: 2
    num_workers: 0

sample_weight_fn:
  name: mean_proportion_class_weight

model:
  name: debug_cnn

loss_func:
  - name: FocalLoss
  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_debug
  parameters:
    epochs: 30



