split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 333

augment_fn:
  name: very_simple_aug_with_elastic_transform
  parameters:
    p: 1
    height: null
    width: null

normalize_fn:
  name: identity

denormalize_fn:
  name: identity

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 32
    val_bs: 32
    test_bs: 32

sample_weight_fn:
  name: create_sample_weights
  parameters:
    method: MEAN

model:
  name: gapnet_resnet34_d_four_channel_input_backbone
  parameters:
    pretrained: false

loss_func:
#  - name: FocalLoss
#    parameters:
#      gamma: 0
  - name: SoftF1Loss


callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping
    parameters:
      clip: 1.0
  - name: CSVLogger

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_gapnet_1
  parameters:
    epochs: 200
    lr: 1e-4



