split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.2
    random_state: 42994442

augment_fn:
  name: very_simple_aug_with_elastic_transform
  parameters:
    p: 1
    height: null
    width: null

normalize_fn:
  name: identity

denormalize_fn:
  name: identity

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 24
    val_bs: 24
    test_bs: 24

sample_weight_fn:
  name: mean_proportion_class_weight
#  name: null
model:
  name: resnet50_four_channel_input
  parameters:
    pretrained: false

loss_func:
  - name: FocalLoss
    parameters:
        gamma: 0
  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping
    parameters:
      clip: 1.0

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: warm_restarts_training_scheme
  parameters:
    lr: 2e-2





