split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 93746

augment_fn:
  name: very_simple_aug_with_elastic_transform
  parameters:
    p: 0.95
    height: null
    width: null

normalize_fn:
  name: four_channel_pnasnet5large_normalize

denormalize_fn:
  name: four_channel_pnasnet5large_denormalize

dataset:
  name: ProteinClassificationDataset

sampler:
  name: null

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 32
    val_bs: 32
    test_bs: 32

model:
  name: pnasnet5large_four_channel_input
  parameters:
    pretrained: true

loss_func:
  - name: FocalLoss
    parameters:
      gamma: 0
#  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping
    parameters:
      clip: 1.0
  - name: CSVLogger

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_3




