# Training functions

# Data loading

LoadTestingData:
  output: test_X
  properties:
    callable_arguments:
      root_image_paths: /home/kevin/Documents/Kaggle/human-protein-image-classification/data/test_combined
  type: load_testing_data

LoadTrainingData:
  type: load_training_data_for_metric_learning
  properties:
    callable_arguments:
      labels_below_count: 10
      root_image_paths:
        - /home/kevin/Documents/Kaggle/human-protein-image-classification/data/train_combined
        - /home/kevin/Documents/Kaggle/human-protein-image-classification/data/train_combined_HPAv18
      root_label_paths: /home/kevin/Documents/Kaggle/human-protein-image-classification/data/train_all_no_dupes.csv
#      use_n_samples: 500
  output:
    - train_X
    - train_y
    - train_y_one_hot

CreateCalculateNumberOfUniqueClasses:
  type: calculate_number_of_unique_classes
  properties:
    callable_arguments:
      labels_one_hot:
        Ref:
          LoadTrainingData: train_y_one_hot
  output: NumberOfUniqueClasses

CreateTrainingDataset:
  output: TrainingDataset
  properties:
    partial_initialization: true
    initialization_arguments:
      augment_fn:
        Ref:
          CreateAugmentationFunction: AugmentationFunction
      open_image_fn:
        Ref:
          CreateOpenImageFunction: OpenImageFunction
      normalize_fn:
        Ref:
          CreateNormalizeFunction: NormalizeFunction
  type: ProteinClassificationDataset

CreateValidationDataset:
  type: ProteinClassificationDataset
  properties:
    partial_initialization: true
    initialization_arguments:
      augment_fn:
        Ref:
          CreateTestAugmentationFunction: TestAugmentationFunction
      open_image_fn:
        Ref:
          CreateOpenImageFunction: OpenImageFunction
      normalize_fn:
        Ref:
          CreateNormalizeFunction: NormalizeFunction
  output: ValidationDataset

CreateTestingDataset:
  type: ProteinClassificationDataset
  properties:
    partial_initialization: true
    initialization_arguments:
      augment_fn:
        Ref:
          CreateTestAugmentationFunction: TestAugmentationFunction
      open_image_fn:
        Ref:
          CreateOpenImageFunction: OpenImageFunction
      normalize_fn:
        Ref:
          CreateNormalizeFunction: NormalizeFunction
  output: TestingDataset

# Image / Augmentation

CreateOpenImageFunction:
  type: open_numpy
  properties:
    callable_arguments:
      with_image_wrapper: true
    partial_callable: true
  output: OpenImageFunction

CreateAugmentationFunction:
  type: crop_rotate90_flip_brightness_elastic
  properties:
    callable_arguments:
      height: 768
      width: 768
      crop_height: 512
      crop_width: 512
      with_image_wrapper: true
  output: AugmentationFunction

CreateTestAugmentationFunction:
  type: resize_aug
  properties:
    callable_arguments:
      height: 768
      width: 768
      with_image_wrapper: true
  output: TestAugmentationFunction

CreateFiveCropTTAFunction:
  type: five_crop_tta_transform
  properties:
    partial_callable: true
    callable_arguments:
      crop_height: 512
      crop_width: 512
  output: FiveCropTTAFunction

#CalculateMeanAndStdForDataset:
#  type: calculate_mean_and_std_for_dataset
#  properties:
#    callable_arguments:
#      data_paths:
#        Ref:
#          - LoadTrainingData: train_X
#          - LoadTestingData: test_X
#  output:
#    - mean
#    - std

CreateNormalizeFunction:
  type: normalize
  properties:
    callable_arguments:
      mean: [12.14099732, 10.9779429,   5.46488976, 22.30204426]
      std: [18.48077492, 17.25324061, 13.88083803, 32.78388995]
    partial_callable: true
  output: NormalizeFunction

CreateDenormalizeFunction:
  type: denormalize
  properties:
    callable_arguments:
      mean: [12.14099732, 10.9779429,   5.46488976, 22.30204426]
      std: [18.48077492, 17.25324061, 13.88083803, 32.78388995]
    partial_callable: true
  output: DenormalizeFunction

#CreateNormalizeFunction:
#  type: identity
#  properties:
#    partial_callable: true
#  output: NormalizeFunction
#
#CreateDenormalizeFunction:
#  type: identity
#  properties:
#    partial_callable: true
#  output: DenormalizeFunction

# Data holding/loading functions

CreateDataBunch:
  type: create_data_bunch
  output: DataBunch
  properties:
    callable_arguments:
      train_X:
        Ref:
          LoadTrainingData: train_X
      train_y_one_hot:
        Ref:
          LoadTrainingData: train_y_one_hot
      train_y:
        Ref:
          LoadTrainingData: train_y
      test_X:
        Ref:
          LoadTestingData: test_X
      train_bs: 32
      test_bs: 4
      val_bs: 4
      train_ds:
        Ref:
          CreateTrainingDataset: TrainingDataset
      test_ds:
        Ref:
          CreateTestingDataset: TestingDataset
      val_ds:
        Ref:
          CreateValidationDataset: ValidationDataset
      sampler:
        Ref:
          CreateSampler: Sampler
      num_workers: 28
    partial_callable: true

CreateSamplerFunction:
  type: uniform_weights
  properties:
    partial_callable: true
  output: SamplerFunction

CreateSampler:
  output: Sampler
  type: create_sampler
  properties:
    callable_arguments:
      sampler_fn:
        Ref:
          CreateSamplerFunction: SamplerFunction
    partial_callable: true

CreateDataSplitter:
  output: DataSplitter
  properties:
    callable_arguments:
      X:
        Ref:
          LoadTrainingData: train_X
      y:
        Ref:
          LoadTrainingData: train_y
    initialization_arguments:
      n_splits: 3
      test_size: 0.2
      random_state: 6969
    callable_function_name: split
    partial_callable: true
  type: StratifiedShuffleSplit

# Training

RunTrainingLoop:
  type: training_loop
  properties:
    callable_arguments:
      create_learner:
        Ref:
          CreateLearner: LearnerCreator
      data_bunch_creator:
        Ref:
          CreateDataBunch: DataBunch
      config_saver:
        Ref:
          SaveConfiguration: ConfigSaver
      data_splitter_iterable:
        Ref:
          CreateDataSplitter: DataSplitter
      training_scheme:
        Ref:
          CreateTrainingScheme: TrainingScheme
      record_results:
        Ref:
          RunRecordResults: ResultRecorder

#CreateTrainingScheme:
#  type: training_scheme_one_cycle
#  properties:
#    callable_arguments:
#      epochs: 80
#      lr: 8e-4
#    partial_callable: true
#  output: TrainingScheme

CreateTrainingScheme:
  type: training_scheme_multi_step
  properties:
    callable_arguments:
      epochs_for_step_for_hyperparameters: [[0, 25, 30, 35, 40]]
      hyperparameter_names: ["lr"]
      hyperparameter_values: [[30e-5, 15e-5, 7.5e-5, 3e-5, 1e-5]]
      end_epoch: 60
    partial_callable: true
  output: TrainingScheme



# Learner for training

CreateLearner:
  type: create_learner
  properties:
    partial_callable: true
    callable_arguments:
      model_creator:
        Ref:
          CreateModel: Model
      metrics:
        Ref:
          - CreateAccuracyMetric: AccuracyMetric
      loss_funcs:
        Ref:
          - CreateArcFaceLoss: ArcFaceLoss
      callbacks_creator:
        Ref:
          CreateCallbacks: CallbacksCreator
      callback_fns_creator:
        Ref:
          CreateLearnerCallbacks: LearnerCallbacksCreator
      to_fp16: true
  output: LearnerCreator

CreateCallbacks:
  type: create_callbacks
  properties:
    partial_callable: true
    callable_arguments:
      callback_references:
        Ref:
          - CreateLabelExtractorCallback: LabelExtractorCallback
  output: CallbacksCreator

CreateLearnerCallbacks:
  type: create_learner_callbacks
  properties:
    partial_callable: true
    callable_arguments:
      learner_callback_references:
        Ref:
          - CreateCSVLoggerLearnerCallback: CSVLoggerLearnerCallback
          - CreateOutputRecorderLearnerCallback: OutputRecorderLearnerCallback
          - CreateGradientClippingLearnerCallback: GradientClippingLearnerCallback
          - CreateSaveModelCallback: SaveModelCallback
          - CreateOutputHookRecorder: OutputHookRecorder
          - CreateTensorBoardRecorderLearnerCallback: TensorBoardRecorder
  output: LearnerCallbacksCreator


# Callbacks
CreateTimeStampedSavePath:
  type: create_time_stamped_save_path
  properties:
    partial_callable: true
    callable_arguments:
      save_path: /media/hd/Kaggle/human-protein-image-classification/results
  output: SavePathCreator

CreateLabelExtractorCallback:
  type: LabelExtractorCallback
  properties:
    partial_initialization: true
  output: LabelExtractorCallback

CreateOutputHookRecorder:
  type: OutputHookRecorder
  properties:
    partial_initialization: true
  output: OutputHookRecorder

CreateSaveModelCallback:
  type: SaveModelCallback
  properties:
    initialization_arguments:
      monitor: val_focal_loss
      save_path_creator:
        Ref:
          CreateTimeStampedSavePath: SavePathCreator
    partial_initialization: true
  output: SaveModelCallback


CreateCSVLoggerLearnerCallback:
  type: create_csv_logger
  properties:
    partial_callable: true
    callable_arguments:
      save_path_creator:
        Ref:
          CreateTimeStampedSavePath: SavePathCreator
  output: CSVLoggerLearnerCallback

CreateTensorBoardRecorderLearnerCallback:
  type: TensorBoardRecorder
  properties:
    partial_initialization: true
    initialization_arguments:
      save_path_creator:
        Ref:
          CreateTimeStampedSavePath: SavePathCreator
  output: TensorBoardRecorder

CreateOutputRecorderLearnerCallback:
  type: create_output_recorder
  properties:
    partial_callable: true
    callable_arguments:
      save_path_creator:
        Ref:
          CreateTimeStampedSavePath: SavePathCreator
      denormalize_fn:
        Ref:
          CreateDenormalizeFunction: DenormalizeFunction
  output: OutputRecorderLearnerCallback

CreateGradientClippingLearnerCallback:
  type: GradientClipping
  properties:
    partial_initialization: true
    initialization_arguments:
      clip: 1.0
  output: GradientClippingLearnerCallback

CreateFiveCropTTAPredictionCallback:
  type: FiveCropTTAPredictionCallback
  properties:
    initialization_arguments:
      aggregate_mode: MEAN
  output: FiveCropTTAPredictionCallback

SaveConfiguration:
  type: save_config
  properties:
    callable_arguments:
      save_path_creator:
        Ref:
          CreateTimeStampedSavePath: SavePathCreator
    partial_callable: true
  output: ConfigSaver

CreateResultRecorder:
  type: ResultRecorder
  properties:
    partial_initialization: true
  output: ResultRecorderCreator

RunRecordResults:
  type: record_results
  properties:
    callable_arguments:
      result_recorder_callback:
        Ref:
          CreateResultRecorder: ResultRecorderCreator
      save_path_creator:
        Ref:
          CreateTimeStampedSavePath: SavePathCreator
    partial_callable: true
  output: ResultRecorder

CreateModel:
  type: resnet50_four_channel_input_arc_margin_product
  properties:
    callable_arguments:
      pretrained: true
      arc_margin_product_n_out:
        Ref:
          CreateCalculateNumberOfUniqueClasses: NumberOfUniqueClasses
    partial_callable: true
  output: Model


CreateArcFaceLoss:
  type: ArcFaceLoss
  output: ArcFaceLoss

CreateAccuracyMetric:
  type: accuracy
  properties:
    partial_callable: true
  output: AccuracyMetric

