split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 333

augment_fn:
  name: very_simple_aug_with_elastic_transform
  parameters:
    p: 0.5
    height: 1024
    width: 1024

normalize_fn:
  name: identity

denormalize_fn:
  name: identity

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 8
    val_bs: 8
    test_bs: 8
    pin_memory: true

sample_weight_fn:
  name: create_sample_weights
  parameters:
    method: MEAN

model:
  name: resnet34_d_four_channel_input_one_fc
  parameters:
    pretrained: false

loss_func:
  - name: FocalLoss
    parameters:
      gamma: 0
#  - name: SoftF1Loss


callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping
    parameters:
      clip: 1.0
  - name: CSVLogger

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_gapnet_1
  parameters:
    epochs: 60
    lr: 3e-3



