split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 333

augment_fn:
  name: very_simple_aug_with_elastic_transform_and_crop
  parameters:
    height: 512
    width: 512

normalize_fn:
  name: identity

denormalize_fn:
  name: identity

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 16
    val_bs: 4
    test_bs: 4

sample_weight_fn:
  name: mean_proportion_class_weight
#  name: null
model:
  name: se_resnext50_32x4d_four_channel_input
  parameters:
    pretrained: false

loss_func:
  - name: FocalLoss
    parameters:
        gamma: 0
#  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping
    parameters:
      clip: 1.0

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_se_resnext50_32x4d
  parameters:
    epochs: 60
    lr: 1e-4





