split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.2
    random_state: 4233

augment_fn:
  name: very_simple_aug_with_elastic_transform
  parameters:
    p: 0.95
    height: null
    width: null

normalize_fn:
  name: four_channel_image_net_normalize

denormalize_fn:
  name: four_channel_image_net_denormalize

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 24
    val_bs: 24
    test_bs: 24

sample_weight_fn:
  name: mean_proportion_class_weight
#  name: null
model:
  name: se_resnext50_32x4d_four_channel_input

loss_func:
  - name: FocalLoss
    parameters:
        gamma: 0.0
  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping
    parameters:
      clip: 1.0

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_se_resnext50_32x4d
  parameters:
    epochs: 75
    lr: 5e-3





