CreateDataBunch:
  output:
  - DataBunch
  properties:
    callable_arguments:
      test_X:
        Ref:
          LoadTestingData: test_X
      test_bs: 64
      test_ds:
        Ref:
          CreateTestingDataset: TestingDataset
      train_X:
        Ref:
          LoadTrainingData: train_X
      train_bs: 32
      train_ds:
        Ref:
          CreateTrainingDataset: TrainingDataset
      train_y:
        Ref:
          LoadTrainingData: train_y
      val_bs: 64
      val_ds:
        Ref:
          CreateValidationDataset: ValidationDataset
    partial_callable: true
  type: create_data_bunch

CreateDataSplitter:
  output:
  - DataSplitter
  properties:
    callable_arguments:
      X:
        Ref:
          LoadTrainingData: train_X
      y:
        Ref:
          LoadTrainingData: train_y
    initialization_arguments:
      n_splits: 5
  type: KFold

CreateLearner:
  properties:
    callable_arguments:
      data_bunch_creator:
        Ref:
          CreateDataBunch: DataBunch
      data_splitter_iterable:
        Ref:
          CreateDataSplitter: DataSplitter
  type: create_learner

CreateTestingDataset:
  output:
  - TestingDataset
  properties:
    partial_initialization: true
  type: MyDataset

CreateTrainingDataset:
  output:
  - TrainingDataset
  properties:
    partial_initialization: true
  type: MyDataset

CreateValidationDataset:
  output:
  - ValidationDataset
  properties:
    partial_initialization: true
  type: MyDataset

LoadTestingData:
  output:
  - test_X
  properties:
    callable_arguments:
      n_samples: 100
  type: load_testing_data

LoadTrainingData:
  output:
  - train_X
  - train_y
  properties:
    callable_arguments:
      n_samples: 100
  type: load_training_data
