split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 42

augment_fn:
  name: simple_aug
  parameters:
    p: 1
    height: null
    width: null

normalize_fn:
  name: identity

denormalize_fn:
  name: identity

dataset:
  name: ProteinClassificationDataset

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 32
    val_bs: 64
    test_bs: 64

sampler:
  name: WeightedRandomSampler
  parameters:
    replacement: true

model:
  name: GapNet

loss_func:
  - name: FocalLoss
  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_gapnet
  parameters:
    epochs: 30
    lr: 2e-4



