split_method:
  name: MultilabelStratifiedShuffleSplit
  parameters:
    n_splits: 1
    test_size: 0.1
    random_state: 42

augment_fn:
  name: very_simple_aug
  parameters:
    p: 1
    height: null
    width: null

normalize_fn:
  name: four_channel_image_net_normalize

denormalize_fn:
  name: four_channel_image_net_denormalize

dataset:
  name: ProteinClassificationDataset

sampler:
  name: null

data_bunch:
  name: DataBunch
  parameters:
    train_bs: 32
    val_bs: 32
    test_bs: 32

model:
  name: resnet50_four_channel_input
  parameters:
    pretrained: true

loss_func:
  - name: FocalLoss
  - name: SoftF1Loss

callbacks:
  - name: NameExtractionTrainer

callback_fns:
  - name: OutputRecorder
  - name: GradientClipping

metrics:
  - name: accuracy
  - name: f1_soft

learner:
  name: Learner

training_scheme:
  name: training_scheme_3




